language: python
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -q -f environment.yml
  - conda activate pyeeglab
  - pip install .
  - conda install -q -y pytest pytest-cov codecov
script: travis_wait 30 pytest --cov=./ && codecov
deploy:
  provider: pypi
  user: AlessioZanga
  password:
    secure: B6JGqiXI8b2dpEfhr+uwanH0/nzRhMff+swHVWAjEoBeQnIigq09FRqfJWEYjE5FNkKDQpmjOKJrDy3HCigMQwIIOHsE3MkftUeANfs6CizJsZgCgij2A+vK2rDP1w3OEaowjh//SDeX8YGWEBRoP2pdWIrE9EnpBC44BftWoZreHNKMYXOnNrk4tUDjNz0gFoy0v0mSMqdWTcOxNqivLykKwKZ1kYFaRLo4WpTRo0KGDHYnBMTE5FnLjogBW9NjiymNRf4m6sEVPPoQBHkVFHFsfh6MB8qOC5cNzoiHv8VmfREBSatUHVxXrBBAC90gWEQAFgJRsF98ikWJznLmXOPvaJbXGvDYEPx6A4/DaBXiQjMPxTK41i/UsetM+CVVs8VfCmWa6oGGLvDKJP5LcZdSXM6vH/3DUoVwR8y3aGuB9aiol+F9HJKUdHavhISf9B5HtJNJA9EDnW0Gq4Bf7ggwgA6q2LTXWk3iwqn5qXDVFdzkWQOmt1nEtmA8GKPykTTsC6tdMLjS1w+ck+d1w7AziMY7nI+8APWbuZ3E+bXYsfRZsddbo+KDSZq97WfADxH7AFtEO4os/czIUtG/4y1wTTEMdCMR/sEZ2eK1uPTB5n4jhoeWGKRz3hkXBAcje7VvPdio+c+gIvco9enbtd1UfEyLosC0co5KtdFqdIg=
  on:
    branch: master
