name: pyeeglab
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python>=3.7,<3.8
    - mne==0.20.0
    - networkx>=2.2
    - nltk
    - numpy
    - scipy
    - pandas
    - sqlalchemy>=1.2
    - wfdb
    # At the moment, YASA is not available
    # on any Conda channel, so defaulting to pip
    - pip
    - pip:
        - yasa>=0.1.6
